name: CI

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    name: run cargo tests
    runs-on: ubuntu-latest
    steps:
    - name: check out branch
      uses: actions/checkout@v4
    - name: set up rust
      uses: actions-rust-lang/setup-rust-toolchain@v1
    - name: cargo build
      run: cargo build --verbose
    - name: cargo test
      run: cargo test --verbose
  lint:
    name: verify formatting and lints
    runs-on: ubuntu-latest
    steps:
    - name: check out branch
      uses: actions/checkout@v4
    - name: set up rust
      uses: actions-rust-lang/setup-rust-toolchain@v1
      with:
        components: rustfmt, clippy
    - name: verify formatting
      uses: actions-rust-lang/rustfmt@v1
    - name: run clippy
      run: cargo clippy -- --deny clippy::all --warn clippy::pedantic --warn warnings
